### PR TITLE
added completion handling

### PR DESCRIPTION
**Pull request by 0-M**
performs an action when image dismissed - on `close()`

added function: `show( targetImageView:UIImageView, completion: () -> Void )`

Usage:

``` swift
    self.imageViewer.show(imageViewToDisplay, completion: {
        println("Add code to be run when image dismissed")
    })
```

### CODE REVIEW

**Comment by 0-M** [comment]
@hiragram do any cocoapods files need updating? is it okay to change just this one file?

**Comment by 0-M** [comment]
@hiragram can you address this pull request?

**Comment by hiragram** [comment]
@mmarkman I can push merge button but I am not working with this library and won't update anymore.
So if you need this library, I can add you as a collaborator.

**Comment by 0-M** [comment]
@hiragram that would be perfect! please merge and then add me as a collaborator. I'm not making any promises, but when I get around to updating my iOS apps I'll try to get this updated too

**Comment by hiragram** [comment]
@mmarkman I'm sorry I have been quiet for an extreme long time. (It has taken one year 🙏 )
I am glad to hear of it.
I add you as a collaborator immediately.

**Pull request merged**
